### ISSUE TITLE
Can't create files: Permissions and/or missing XDG variable

### ISSUE THREAD

**Issue by Philip-Scott** [flathub/com.github.philip_scott.spice-up#1]
From: https://github.com/Philip-Scott/Spice-up/issues/166

```
[FATAL 12:04:28.428795] file /run/build/spiceup/src/Services/FileManager.vala: 
line 100: uncaught error: Failed to create file “/home/sri/Downloads/(null)/Untitled Presentation 1.spice.KKC07Y”: 
No such file or directory (g-file-error-quark, 4)
```

The file manager tries to first get the documents dir for saving the presentations with:
```vala
var documents = Environment.get_user_special_dir (UserDirectory.DOCUMENTS) + "/%s".printf (_("Presentations"));
DirUtils.create_with_parents (documents, 0775); 
```
About the env variable: https://valadoc.org/glib-2.0/GLib.Environment.get_user_special_dir.html

This is an XDG special user dir that isn't being set up, and returns null if it's not found 
(that's my bad for not catching the null, which i will fix on the next version)

**Comment by TingPing** [comment]
We should be passing `--filesystem=xdg-documents`. Also I don't know if I mentioned it before but we shouldn't be granting access to home and the application should be using GtkFileChooserNative any time it needs to save/load something outside of documents.

**Comment by Philip-Scott** [comment]
Hmm... in that case, don't fix it and leave it as null

That way, if a null gets returned, i could just open the GtkFileChooser and let the user pick the location and everything, right?

do i need to do something else from my end?

**Comment by Philip-Scott** [comment]
Actually, if the app always needs the GtkFileChooser, some things like the presentation browser will probably not work anymore. Is there a special dir that flatpak apps have always read and write access to? (Like how sandboxed apps work in iOS?)

**Comment by TingPing** [comment]
Passing `xdg-documents` is probably reasonable but I do believe if it returns `NULL` its probably not a bad idea to ask the user.

**Comment by TingPing** [comment]
> Is there a special dir that flatpak apps have always read and write access to? 

`$XDG_DATA_HOME` will always work.
