### ISSUE TITLE
Default open file dialog does not list ".spice" files

### ISSUE THREAD

**Issue by rugk** [flathub/com.github.philip_scott.spice-up#3]
The default file dialog does not list the ".spice" files. I have to select "All files" instead of "Presentations" (at the bottom right) in order to be able to select the correct file.

installed from Flathub
GNOME v3.26
Fedora 27

**Comment by rugk** [comment]
Also affects the opening dialog: https://github.com/flathub/com.github.philip_scott.spice-up/issues/3

**Comment by TingPing** [comment]
Upstream needs to rename their mime file to match their app-id. Not sure why @Philip-Scott closed the upstream issues.

**Comment by Philip-Scott** [comment]
Yeah, higher up having the `-` before the last element is invalid :/, so it can't have `philip-scott` 

Thank you for taking care of this :)

**Comment by TingPing** [comment]
@Philip-Scott For what its worth these requirements are being proposed to be part of the DBus spec (thus Gtk) so you'll have to rename eventually.

**Comment by Philip-Scott** [comment]
@tingping do you know who Is in charge of proposing that? Maybe I can talk to them about it because dashes and underscores are perfectly normal to be part of a URI

**Comment by TingPing** [comment]
DBus isn't a URI and has never matched that behavior, I'll try to find the bug report though.

**Comment by TingPing** [comment]
https://bugzilla.freedesktop.org/show_bug.cgi?id=103914
