### ISSUE TITLE
Update 1.3.0

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.github.philip_scott.spice-up#4]

**Comment by nedrichards** [comment]
Patches welcome! Feel free to propose a PR with an update, otherwise I'll get to it soon.

**Comment by LeandroStanger** [comment]
https://github.com/flathub/com.github.philip_scott.spice-up/compare/master...LeandroStanger:patch-1

**Comment by nedrichards** [comment]
You need to update the SHA256 as well for that to work. You can use the `sha256sum` command to get that after you download the archive yourself. You should also check upstream to see if any other library dependencies need to be updated.

It'd probably be best to clone the repo (hit the git clone button) make the update locally and then test with a command such as `flatpak-builder --force-clean  --require-changes --repo=repo app com.github.philip_scott.spice-up.json ` For this app you'll also need to redo the patch that's there - which may be a little harder for you - it might be better to try the route I mentioned above on another app.

**Comment by LeandroStanger** [comment]
https://github.com/flathub/com.github.philip_scott.spice-up/compare/master...LeandroStanger:patch-2

**Comment by LeandroStanger** [comment]
https://github.com/flathub/com.github.philip_scott.spice-up/compare/master...LeandroStanger:patch-3

**Comment by LeandroStanger** [comment]
https://github.com/flathub/com.github.philip_scott.spice-up/compare/master...LeandroStanger:patch-4
