### ISSUE TITLE
Update flatpak to the Juno base 

### ISSUE THREAD

**Issue by Philip-Scott** [flathub/com.github.philip_scott.spice-up#8]
So the most recent version of Spice-Up now depends on some libraries and changes available from elementary Juno (Ubuntu 18.04) Is there a base we can use that contains that? :) 

https://github.com/flathub/com.github.philip_scott.spice-up/blob/89a24a15e2294c87b5a9f83b34dd67660e162edb/com.github.philip_scott.spice-up.json#L3

**Comment by TingPing** [comment]
See https://github.com/flathub/flathub/pull/658

**Comment by bilelmoussaoui** [comment]
Should be fixed with this https://github.com/flathub/com.github.philip_scott.spice-up/pull/10

**Comment by Naheem** [comment]
Any updates with this?

**Comment by nedrichards** [comment]
@Naheem can you test the build in that PR?

**Comment by Naheem** [comment]
I ave tried build 359. It works.
